---
puppet_enterprise::profile::puppetdb::java_args:
  Xmx: '512m'
  Xms: '512m'
puppet_enterprise::profile::master::java_args:
  Xmx: '2048m'
  Xms: '2048m'
puppet_enterprise::profile::console::java_args:
  Xmx: '1024m'
  Xms: '1024m'
